name: Build and Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  pull-requests: write
  contents: read

# Gotta do this for clang-tidy to work
env:
  CONAN_HOME: ${{ github.workspace }}/.conan

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build
      shell: bash
      run: ./build.sh $(pwd)

    - name: Post PR comment for warnings/errors
      if: ${{ always() }} && github.ref != 'refs/heads/main'
      uses: JacobDomagala/CompileResultAction@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        comment_title: UBUNTU COMPILE RESULT
        compile_result_file: ${{ github.workspace }}/build/output.txt

    - name: setup init_script
      shell: bash
      run: |
        echo "#!/bin/bash

        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-ubuntu2404.pin
        mv cuda-ubuntu2404.pin /etc/apt/preferences.d/cuda-repository-pin-600

        wget https://developer.download.nvidia.com/compute/cuda/12.8.0/local_installers/cuda-repo-ubuntu2404-12-8-local_12.8.0-570.86.10-1_amd64.deb
        dpkg -i cuda-repo-ubuntu2404-12-8-local_12.8.0-570.86.10-1_amd64.deb

        cp /var/cuda-repo-ubuntu2404-12-8-local/cuda-*-keyring.gpg /usr/share/keyrings/

        apt-get update
        apt-get -y install cuda-toolkit-12-8

        " > init_script.sh

    - name: Static Analysis
      uses: JacobDomagala/StaticAnalysis@master
      with:
        init_script: init_script.sh
        compile_commands: build/compile_commands.json
        compile_commands_replace_prefix: true
        verbose: true
        clang_tidy_args: |
            -extra-arg=-std=c++20
        cppcheck_args: |
            --enable=all
            --suppress=missingIncludeSystem
            --suppress=functionStatic
            --suppress=unusedFunction
            --inline-suppr
            --inconclusive
            --check-level=exhaustive
