name: Ubuntu

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Run Script
      shell: bash
      run: |
        ./build.sh

    - name: Post PR comment for warnings/errors
      if: ${{ always() }} && github.ref != 'refs/heads/main'
      uses: JacobDomagala/CompileResultAction@master
      with:
        comment_title: UBUNTU COMPILE RESULT
        compile_result_file: ${{runner.workspace}}/build/output.txt
