name: Build and Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  pull-requests: write
  contents: read

# Gotta do this for clang-tidy to work
env:
  CONAN_HOME: ${{ github.workspace }}/.conan

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build
      shell: bash
      run: ./build.sh $(pwd)

    - name: Post PR comment for warnings/errors
      if: ${{ always() }} && github.ref != 'refs/heads/main'
      uses: JacobDomagala/CompileResultAction@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        comment_title: UBUNTU COMPILE RESULT
        compile_result_file: ${{ github.workspace }}/build/output.txt

    - name: Static Analysis
      uses: JacobDomagala/StaticAnalysis@master
      with:
        init_script: init_script.sh
        compile_commands: build/compile_commands.json
        compile_commands_replace_prefix: true
        apt_pckgs: cuda‑minimal‑build‑12‑8
        verbose: true
        clang_tidy_args: |
            -extra-arg=-std=c++20
        cppcheck_args: |
            --enable=all
            --suppress=missingIncludeSystem
            --suppress=functionStatic
            --suppress=unusedFunction
            --inline-suppr
            --inconclusive
            --check-level=exhaustive

