name: Ubuntu

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@master
